import type {Metadata} from "next";

import "./globals.css";

export const metadata: Metadata = {
  title: "PaisaBank",
  description: "Generated by appncy",
};

export default async function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="en">
      <body className="min-h-screen w-full gap-8 font-sans antialiased">{children}</body>
    </html>
  );
}
